### ISSUE TITLE
Compiling for windows?

### ISSUE THREAD

**Issue by theAeon** [conda-forge/r-hdf5r-feedstock#23]
### Comment:

Hi-I was looking at the CRAN page for r-hdf5r and it seems the package does compile for windows. How difficult would that be to enable on the feedstock?

**Comment by ocefpaf** [comment]
Possible? Yes! Easy, sadly no. Windows is always super hard. If you have knowledge on Windows stuff please send a PR. We can also try to re-package the binary like how we  do for `r-rgdal`.

**Comment by theAeon** [comment]
I'll take a look at it. Not super versed on the conda side of things with windows.

**Comment by ocefpaf** [comment]
Take a look here for some inspirations if you want to go the re-packaging route: https://github.com/conda-forge/r-rgdal-feedstock/blob/main/recipe/meta.yaml

**Comment by dipterix** [comment]
@theAeon hdf5r has windows build now. ([Check PR here](https://github.com/conda-forge/r-hdf5r-feedstock/pull/26))
